### ISSUE TITLE
Add `goliothctl` commands

### ISSUE THREAD

**Issue by beriberikix** [goliothlabs/setup-goliothctl#1]
In Slack @sam-golioth had the following suggestion:

_It would be great to wrap the other goliothctl commands into GitHub Actions too instead of shelling out. E.g. instead of `golitothctl dfu artifact create esp-air-quality-monitor.bin --version ${{ steps.get_version.outputs.version-without-v }}` we could have something that feels more native like:_
```
- uses: goliothlabs/create-artifact@main
  with:
    file: esp-air-quality-monitor.bin
    version: ${{ steps.get_version.outputs.version-without-v }}
```

What other commands would be useful in this context?
